---
cluster_name: "{{ rancher_obs_cluster_name | default('mosip_obs') }}"
cluster_dir: "{{ rancher_obs_base_dir | default(ansible_env.HOME | default('/home/ubuntu') + '/rancher/obs') | replace('~', ansible_env.HOME) }}"
rke2_config_dir: "{{ rke2_obs_config_dir | default('/etc/rancher/rke2') }}"
rke2_token_file: "{{ cluster_dir }}/rke2_token"
rke2_cluster_exists: "{{ rke2_obs_cluster_exists | default(false) }}"
rke2_primary_group: "mosip_obs"
rke2_kubeconfig_delegate_host: "{{ groups['mosip_obs'][0] }}"
check_existing_config: "{{ rancher_obs_check_existing_config | default(true) }}"
# Fallback if not set in group_vars/all.yml; set rke2_version there to override.
rke2_version: "v1.28.8+rke2r1"
