---
cluster_dir: "{{ rancher_base_dir }}/{{ cluster_name }}"
rke2_config_dir: "{{ ansible_env.HOME | default('/home/ubuntu') }}/rancher/{{ cluster_name }}/rke2"
rke2_token_file: "{{ cluster_dir }}/rke2_token"
ssh_key_path: "~/.ssh/id_ed25519"
